/*
 *  Copyright 2008-2010 the original author or authors.
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package org.aoplib4j.uml;


import java.io.File;

import org.aoplib4j.TestHelperClass;
import org.junit.AfterClass;
import org.junit.BeforeClass;

/**
 * Base class for all the sequence diagram tests.
 * Contains common code (constants, methods, etc).
 * 
 * @author Adrian Citu
 *
 */
public abstract class UmlTest {

    ActorClass ac = new ActorClass();
    
    public static final String SEQ_EXTENSION = "seq.txt";
    
    public static final String TMP_FOLDER = TestHelperClass.getJavaIoTmpDir();
    
    public static final String DIAGRAMS_FOLDER = "/aoplib4jtests";
    
    public static final String PACKAGE = "/org/aoplib4j/uml";
    
    /**
     * create the folder for the diagrams generated by the tests.
     *
     * @throws java.lang.Exception
     */
    @BeforeClass
    public static void setUpBeforeClass() throws Exception {
        new File(DIAGRAMS_FOLDER).mkdir();
    }

    /**
     * remove the folder containing the diagrams generated by the tests.
     */
    @AfterClass
    public static void tearDownAfterClass() throws Exception {
        //new File(DIAGRAMS_FOLDER).delete();
    }

}
